[package]
name = "term_visualizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
safav = { path = "../.." }
inquire = "0.5.2"
colored = "2.0.0"
palette = "0.6.1"
termsize = "0.1.6"